### PR TITLE
FIX: oa-verify api now able to connect to local blockchain emulator

### PR DESCRIPTION
**Pull request by Neketek**
Changed the way oa-verify api handles the connection to the blockchain. Adam needs this in order to play with the whole trade portal locally.

### CODE REVIEW

**Comment by koriaf** [comment]
Will merging it break anything in the cloud setup assuming it gets no changes? Or some env variables should be added/removed?

**Comment by Neketek** [comment]
@koriaf It changes the way oa verify connects to the blockchain as well as the environment config.  But, honestly, I'm unsure how it works now. Probably, it's set up to work with our infura node, but now we'll be able to use our geth nodes instead as we seem to do everywhere else.

**Comment by Neketek** [comment]
@koriaf We better ask @roleyfoley about this. 
@roleyfoley Please, tell us is it possible to merge without breaking something important?

**Comment by koriaf** [comment]
We have old variable (which is removed in this PR) set; test setups have `ropstein` there. https://github.com/trustbridge/trustbridge-hamlet/search?q=ETHEREUM_NETWORK

Please provide new values for the new variable both for test setups (c1/c2) and for upper ones (using real mainnet) so @roleyfoley can quickly update it (or explain how to calculate them)

**Comment by Neketek** [comment]
@koriaf Unfortunately, I'm unable to provide them, but they are quite easy to get. They should point to any node that is connected to the network that we use to operate. We can even use infura nodes if we have them, in this case endpoint URL will look the next way ```https://ropsten.infura.io/v3/<api key>```. At least it works with OA developers infura node.  Therefore, I assume, updating the config for oa-verify API should not be a problem at all.

**Comment by adamkerz** [comment]
@roleyfoley I have little understanding of what components exist and how they relate to each other, nor how they are deployed - what would need to change to the existing deployment to get this to work? Something like this? `BLOCKCHAIN_ENDPOINT: http://tradetrust-ganache-cli:8585`

**Comment by arpentnoir** [comment]
@adamkerz Yes, it may be the case that that container already has that env var. Will take a look once I'm out of this uber

**Comment by arpentnoir** [comment]
yep, looks like it's already there. I'm going to merge and assume it won't explode.

**Pull request merged**
