### PR TITLE
feat(pdf): Use different way to parse the first page of PDF document

### PR DESCRIPTION
**Pull request by koriaf**
gs-gs/ha-igl-p2#485

@mrtnmrtn?

### CODE REVIEW

**Review by mrtnmrtn — APPROVED** [review]
Without running it, code changes look good.

**Comment by mrtnmrtn** [comment]
@koriaf - I'm happy for this to be merged. What's the process, do you need me to do it or are you okay with doing the merge?

**Comment by arpentnoir** [comment]
@koriaf how snappy is the image creation on your machine? maybe we could look at adding a spinner while the image is being created, quite laggy on my machine so just see a blank page with qr for quite a while. but the whole thing runs quite slow on my machine so maybe it'll be ok once deployed...

**Comment by koriaf** [comment]
it works completely fine and in no time for me; let's see how it works on integration. if the delay is more than 1s then spinner is a good idea

**Comment by koriaf** [comment]
works subjectively fast for me (https://trade.c1.devnet.trustbridge.io/documents/d1ef2ffa-8fc1-4299-b43b-515946c71324/documents/pdf/?inline=true&as_png=true&original=true)

**Comment by arpentnoir** [comment]
yep, it was like 5 seconds for me locally but immediate on devnet

**Pull request merged**
