### PR TITLE
feat(UX): Harmonise the UX with #107

### PR DESCRIPTION
**Pull request by webilhan**
Related tickets: gs-gs/ha-igl-project#128, gs-gs/ha-igl-project#129, gs-gs/ha-igl-project#130, gs-gs/ha-igl-project#131, gs-gs/ha-igl-project#132, gs-gs/ha-igl-project#133

### CODE REVIEW

**Comment by mrtnmrtn** [comment]
@arpentnoir - are you able to review this? I haven't got the code running on my local machine.

**Comment by arpentnoir** [comment]
this is what the trade portal looks like on my machine when running up this PR... 

Screen Shot 2021-02-10 at 9 40 00 am
this looks to me like gs-gs/ha-igl-project#128 not done

in general, @webilhan it would be better if you could address each ticket with a single commit and include visual evidence in the PR. so that, when reviewing the PR I can see - this is the issue being fixed, this is the specific change to address that fix, this is visual proof of the change...

**Comment by webilhan** [comment]
@arpentnoir Did you compile CSS styles, by running `npm install && npm run build`.
It is hard to make separate PR for each ticket because they are quite connected. Is it important to make it separate PR per each ticket, should I redo it?

**Comment by arpentnoir** [comment]
Fresh clone, ran npm install then build, yes.

Not necessary to do separate PRs, no. But separate commits makes the changes easier to track

**Comment by arpentnoir** [comment]
Maybe it was cache. I'll take another look soon and let you know...

**Comment by koriaf** [comment]
Quickly checked it, builds fine and there are some visible changes.

**Comment by arpentnoir** [comment]
yep, sorry @webilhan looks like it was cache

**Pull request merged**
